#!/usr/bin/env python3
"""Generate main/flip_font.h: anti-aliased digit bitmaps for the flip clock cards.

Each digit is pre-rendered centred in a card-sized cell as 8-bit alpha, so the
firmware can draw a card row-by-row (and squash it for the flip animation).

Usage:  pip install pillow
        python3 tools/gen_flip_font.py
"""
import os
from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/dejavu-sans-fonts/DejaVuSansCondensed-Bold.ttf"
SUPERSAMPLE = 4
OUT = os.path.join(os.path.dirname(__file__), "..", "main", "flip_font.h")

# name, card width, card height, digit height in pixels
SIZES = [
    ("flip_font_large", 42, 66, 46),
    ("flip_font_small", 22, 34, 23),
]


def render(w, h, digit_height, max_width):
    """Render digits supersampled, then scale them to `digit_height`, squeezing
    horizontally if needed so the widest digit fits in `max_width`."""
    font = ImageFont.truetype(FONT, digit_height * SUPERSAMPLE * 2)
    _, top, _, bottom = font.getbbox("0")
    boxes = [font.getbbox(d) for d in "0123456789"]
    widest = max(b[2] - b[0] for b in boxes)
    sy = digit_height / (bottom - top)
    sx = min(sy, max_width / widest)

    glyphs = []
    for d, (left, _, right, _) in zip("0123456789", boxes):
        big = Image.new("L", (right - left, bottom - top), 0)
        ImageDraw.Draw(big).text((-left, -top), d, font=font, fill=255)
        gw = max(1, round((right - left) * sx))
        small = big.resize((gw, digit_height), Image.LANCZOS)
        cell = Image.new("L", (w, h), 0)
        cell.paste(small, ((w - gw) // 2, (h - digit_height) // 2))
        glyphs.append(list(cell.getdata()))
    return glyphs


def main():
    out = [
        "// Generated by tools/gen_flip_font.py - do not edit",
        "// Digits rendered from DejaVu Sans Condensed Bold (Bitstream Vera licence)",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    int width, height;",
        "    const uint8_t *digits[10]; // width*height alpha values each",
        "} flip_font_t;",
        "",
    ]
    for name, w, h, dh in SIZES:
        glyphs = render(w, h, dh, w * 4 // 5)
        for i, g in enumerate(glyphs):
            out.append(f"static const uint8_t {name}_{i}[{w * h}] = {{")
            for row in range(h):
                out.append("    " + ",".join(str(v) for v in g[row * w:(row + 1) * w]) + ",")
            out.append("};")
        refs = ", ".join(f"{name}_{i}" for i in range(10))
        out.append(f"static const flip_font_t {name} = {{ {w}, {h}, {{ {refs} }} }};")
        out.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
